data_loader:

  data_file_list: ['/pscratch/sd/s/sydney3/project3/train100k_seed1.h5']
  #['/Users/smericks/Desktop/StrongLensing/project3/slsim/slsim/TrainingSets/100ktraining_seed1.h5']
  
  image_type: 'image_flux_Roman_F158'
  parameter_labels: [
    # deflector mass params
    'deflector_LOG_theta_E','los_gamma1','los_gamma2',
    'deflector_LOG_gamma_pl','deflector_e1_mass','deflector_e2_mass',
    # deflector light params
    'deflector_e1_light','deflector_e2_light','deflector_LOG_angular_size',
    'deflector_n_sersic',
    # source params
    'source_center_x','source_center_y','source_LOG_angular_size']

# Feature extractor 
feature_extractor:
  network_architecture: cnn # network_architecture: resnet34, cnn
  feature_dim: 64
  weights: null # resnet34
  input_shape: [66, 66] # cnn
  in_channels: 1 # cnn
  out_channels_per_layer: [16, 32, 64, 128] # cnn
  num_conv_layers: 4 # cnn
  num_linear_layers: 3 # cnn
  num_linear_units: 128
  kernel_size: 3 # cnn
  pool_kernel_size: 2 # cnn

posterior_estimator:
  density_estimator: mdn # density_estimator: maf, nsf, maf_rqs, mdn
  z_score_theta: independent
  z_score_x: structured
  hidden_features: 128
  num_transforms: 10
  num_components: 1
  num_bins: 10
  use_batch_norm: true

sbi_trainer:
  batch_size: 256
  learning_rate: 0.00005 # LEARNING RATE!
  validation_fraction: 0.15
  stop_after_epochs: 5
  max_num_epochs: 2147483647
  resume_training: false
  retrain_from_scratch: false
  show_train_summary: true
  show_progress_bars: true

misc:
  save_directory: "/pscratch/sd/s/sydney3/project3/" #"/Users/smericks/Desktop/StrongLensing/project3/sbi-stronglensing/" # CHANGE THIS
  save_loss_plot: true